### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vovapraded**

### CODE REVIEW

**Comment by worthant** [comment]
Hi!) Thanks for contribution to my project, however i have some comments about this PR:

1. I already have a note that suggests moving .war into wildfly deployments directory:
image

2. There is no strict rule to use `javax`, for example, i'm using `jakarta` in a 3rd laboratory work:
https://github.com/worthant/interactive-graph-ui/blob/a13196e96ccde00697b9c7fa1db9fff15df5e262/pom.xml

> Just use which one is compatible with other environment that you're using. I don't remember strictly which one is better (javax/jakarta) in which cases, but yes, there are some compatibility issues, and they're individual

In summary, just don't use java please.

**Comment by worthant** [comment]
If you still think i need to improve something - please respond in a form of another comment.
If you think that there is no need - just close PR :)

**Comment by vovapraded** [comment]
можно написать что при ошибках ClassNotDefine поробовать сменить одно на другое

**Comment by worthant** [comment]
> можно написать что при ошибках ClassNotDefine поробовать сменить одно на другое

Ну тк напиши :)

**Pull request closed without merging**
